name: Refresh latest posts from website

on:
  workflow_dispatch:
  schedule:
    - cron: "12 2 * * 1"

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<actions@github.com>"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Run
        run: ./build.py

      - name: Check if there's any changes
        id: verify_diff
        run: |
          if [ -n "$(git status --porcelain)" ]; then echo ::set-output name=changed::true; fi

      - name: Commit and push
        if: steps.verify_diff.outputs.changed == 'true'
        run: |
          git add *.md
          git commit -m "New/Modified Observations"
          git push origin main